# Generated by Django 5.1.15 on 2025-12-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("openai_api_key", models.CharField(blank=True, default="", max_length=500)),
                ("confluence_site_url", models.URLField(blank=True, default="")),
                ("confluence_api_token", models.CharField(blank=True, default="", max_length=500)),
                ("confluence_user_email", models.EmailField(blank=True, default="", max_length=254)),
                ("confluence_space_key", models.CharField(blank=True, default="", max_length=50)),
                ("confluence_parent_page_id", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="setting", to="ai_meeting_teams.team"
                    ),
                ),
            ],
            options={
                "db_table": "team_settings",
            },
        ),
    ]
