# Generated by Django 5.1.15 on 2025-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_meeting_teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamsetting",
            name="slack_bot_token",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="teamsetting",
            name="slack_default_channel",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="teamsetting",
            name="slack_webhook_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
