# Generated by Django 5.1.15 on 2025-12-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_meeting_teams", "0001_initial"),
        ("ai_meeting_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_team_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="ai_meeting_teams.team",
            ),
        ),
    ]
