# Generated by Django 5.1.15 on 2025-12-12 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ai_meeting_meetings.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_meeting_teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("meeting_date", models.DateTimeField()),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to=ai_meeting_meetings.models.audio_file_path),
                ),
                ("audio_file_expires_at", models.DateTimeField(blank=True, null=True)),
                ("transcript", models.TextField(blank=True, default="")),
                ("speaker_data", models.JSONField(blank=True, default=list)),
                ("corrected_transcript", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("compressing", "압축 중"),
                            ("transcribing", "STT 처리 중"),
                            ("correcting", "텍스트 교정 중"),
                            ("summarizing", "요약 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("confluence_page_id", models.CharField(blank=True, default="", max_length=50)),
                ("confluence_page_url", models.URLField(blank=True, default="")),
                ("slack_message_ts", models.CharField(blank=True, default="", max_length=50)),
                ("slack_channel", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="meetings", to="ai_meeting_teams.team"
                    ),
                ),
            ],
            options={
                "db_table": "meetings",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("speaker_label", models.CharField(max_length=50)),
                ("speaker_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_mappings",
                        to="ai_meeting_meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "speaker_mappings",
                "unique_together": {("meeting", "speaker_label")},
            },
        ),
    ]
