# Generated by Django 5.1.15 on 2025-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_meeting_meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="corrected_speaker_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
